# docker-compose.yml (com sua senha personalizada)
version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: gaming_neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt connection
    environment:
      # Usando sua senha personalizada
      - NEO4J_AUTH=neo4j/gamepass123
      # Configurações de memória
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms.memory.heap.initial_size=512M
      - NEO4J_dbms.memory.heap.max_size=512M
      # Configurações de conectividade
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p gamepass123 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  neo4j_data:
  neo4j_logs: